apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort  # Exposes service on node's IP
  selector:
    app: backend
  ports:
  - port: 8000        # Port inside cluster
    targetPort: 8000  # Port on pod
    nodePort: 30800   # Port on EC2 (30000-32767 range)
  sessionAffinity: ClientIP  # Sticky sessions